import fs from "node:fs";
import path from "node:path";
import { resolveCliConfig } from "../public/config";

export const CMAKE_INTEGRATION_FILE_NAME = "cppkg.cmake";

export type GenerateCMakeIntegrationOptions = {
  force?: boolean;
  output?: string;
};

function normalizeProjectRelativeOutput(value: string) {
  const normalized = value.trim().replace(/\\/g, "/").replace(/^\.\/+/, "");

  if (!normalized) {
    throw new Error("Option --output cannot be empty.");
  }

  if (path.isAbsolute(normalized)) {
    throw new Error("Option --output must be a relative project path.");
  }

  const segments = normalized.split("/").filter(Boolean);

  if (!segments.length || segments.some((segment) => segment === "." || segment === "..")) {
    throw new Error("Option --output must stay inside the current project.");
  }

  return segments.join("/");
}

function toCMakeRelativePath(fromDirectory: string, targetPath: string) {
  const relativePath = path.relative(fromDirectory, targetPath).replace(/\\/g, "/");

  if (!relativePath) {
    return ".";
  }

  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

function renderCMakeIntegration(outputPath: string) {
  const config = resolveCliConfig();
  const outputDir = path.dirname(outputPath);
  const packageRootPath = path.resolve(process.cwd(), config.packageRootDir);
  const packageRootRelative = toCMakeRelativePath(outputDir, packageRootPath);

  return [
    "# Generated by cppkg-cli.",
    "include_guard(GLOBAL)",
    "",
    `set(CPPKG_ROOT "\${CMAKE_CURRENT_LIST_DIR}/${packageRootRelative}")`,
    `set(CPPKG_INCLUDE_DIR "\${CPPKG_ROOT}/${config.includeDirName}")`,
    `set(CPPKG_PROJECTS_DIR "\${CPPKG_ROOT}/${config.projectsDirName}")`,
    "",
    "add_library(cppkg_headers INTERFACE)",
    "add_library(cppkg::headers ALIAS cppkg_headers)",
    "",
    "if(EXISTS \"${CPPKG_INCLUDE_DIR}\")",
    "  target_include_directories(cppkg_headers INTERFACE \"${CPPKG_INCLUDE_DIR}\")",
    "  if(CPPKG_GLOBAL_INCLUDE_DIRECTORIES)",
    "    include_directories(\"${CPPKG_INCLUDE_DIR}\")",
    "  endif()",
    "endif()",
    "",
    "option(CPPKG_ADD_PROJECTS \"Add cppkg full-project installs with add_subdirectory\" ON)",
    "",
    "if(CPPKG_ADD_PROJECTS AND EXISTS \"${CPPKG_PROJECTS_DIR}\")",
    "  file(GLOB CPPKG_PROJECT_CMAKE_LISTS CONFIGURE_DEPENDS \"${CPPKG_PROJECTS_DIR}/*/CMakeLists.txt\")",
    "  foreach(CPPKG_PROJECT_CMAKE_LIST IN LISTS CPPKG_PROJECT_CMAKE_LISTS)",
    "    get_filename_component(CPPKG_PROJECT_DIR \"${CPPKG_PROJECT_CMAKE_LIST}\" DIRECTORY)",
    "    get_filename_component(CPPKG_PROJECT_NAME \"${CPPKG_PROJECT_DIR}\" NAME)",
    "    add_subdirectory(",
    "      \"${CPPKG_PROJECT_DIR}\"",
    "      \"${CMAKE_BINARY_DIR}/cppkg-projects/${CPPKG_PROJECT_NAME}\"",
    "      EXCLUDE_FROM_ALL",
    "    )",
    "  endforeach()",
    "endif()",
    "",
  ].join("\n");
}

export function generateCMakeIntegration(
  options: GenerateCMakeIntegrationOptions = {},
) {
  const output = options.output
    ? normalizeProjectRelativeOutput(options.output)
    : CMAKE_INTEGRATION_FILE_NAME;
  const outputPath = path.resolve(process.cwd(), output);

  if (fs.existsSync(outputPath) && !options.force) {
    throw new Error(
      `${output} already exists. Use --force to overwrite it.`,
    );
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, renderCMakeIntegration(outputPath), "utf8");

  return {
    outputPath,
  };
}
